// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooApp.Infrastructure.Persistence;

#nullable disable

namespace ZooApp.Infrastructure.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20251206194658_FixedZooKeeper")]
    partial class FixedZooKeeper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooApp.Domain.Animal.Animal", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTimeFed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ZooApp.Domain.Vet.Vet", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MonthlyHoursLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vets");
                });

            modelBuilder.Entity("ZooApp.Domain.Vet.Visit", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("AnimalId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VetId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("ZooKeeperId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ZooKeeperId");

                    b.ToTable("ZooKeeperTasks", (string)null);

                    b.HasDiscriminator<string>("TaskType").HasValue("AbstractTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.ZooKeeper", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonthlyHoursLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ZooKeepers");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AnimalRelatedTask", b =>
                {
                    b.HasBaseType("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask");

                    b.Property<decimal>("AnimalId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("TargetAnimalId");

                    b.HasDiscriminator().HasValue("AnimalRelated");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.OtherTask", b =>
                {
                    b.HasBaseType("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask");

                    b.HasDiscriminator().HasValue("Other");
                });

            modelBuilder.Entity("ZooApp.Domain.Animal.Animal", b =>
                {
                    b.OwnsOne("ZooApp.Domain.Animal.Species", "Species", b1 =>
                        {
                            b1.Property<decimal>("AnimalId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<int>("FeedingIntervalInHours")
                                .HasColumnType("integer")
                                .HasColumnName("FeedingInterval");

                            b1.Property<string>("Kingdom")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Kingdom");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SpeciesName");

                            b1.HasKey("AnimalId");

                            b1.ToTable("Animals");

                            b1.WithOwner()
                                .HasForeignKey("AnimalId");
                        });

                    b.Navigation("Species")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.Vet.Visit", b =>
                {
                    b.HasOne("ZooApp.Domain.Vet.Vet", null)
                        .WithMany("Visits")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask", b =>
                {
                    b.HasOne("ZooApp.Domain.ZooKeeper.ZooKeeper", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ZooKeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.Vet.Vet", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.ZooKeeper", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
