// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooApp.Infrastructure.Persistance;

#nullable disable

namespace ZooApp.Infrastructure.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    [Migration("20260105203443_UpdateCreateTaskProcedure")]
    partial class UpdateCreateTaskProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooApp.Domain.Animal.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTimeFed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ZooApp.Domain.Species.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedingIntervalInHours")
                        .HasColumnType("integer");

                    b.Property<string>("Kingdom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Species", (string)null);
                });

            modelBuilder.Entity("ZooApp.Domain.Vets.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MonthlyHoursLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Vets");
                });

            modelBuilder.Entity("ZooApp.Domain.Vets.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VetId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("ZooKeeperId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZooKeeperId");

                    b.ToTable("ZooKeeperTasks", (string)null);

                    b.HasDiscriminator<string>("TaskType").HasValue("AbstractTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.ZooKeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonthlyHoursLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ZooKeepers");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AnimalRelatedTask", b =>
                {
                    b.HasBaseType("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetAnimalId");

                    b.HasDiscriminator().HasValue("AnimalRelated");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.OtherTask", b =>
                {
                    b.HasBaseType("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask");

                    b.HasDiscriminator().HasValue("Other");
                });

            modelBuilder.Entity("ZooApp.Domain.Animal.Animal", b =>
                {
                    b.HasOne("ZooApp.Domain.Species.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.Vets.Visit", b =>
                {
                    b.HasOne("ZooApp.Domain.Vets.Vet", null)
                        .WithMany("Visits")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.Tasks.AbstractTask", b =>
                {
                    b.HasOne("ZooApp.Domain.ZooKeeper.ZooKeeper", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ZooKeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooApp.Domain.Vets.Vet", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ZooApp.Domain.ZooKeeper.ZooKeeper", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
